"""create users table

Revision ID: dc523611cd74
Revises: 
Create Date: 2025-11-05 16:01:36.044340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc523611cd74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)

    op.create_table('user_badges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'badge_id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_table('user_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('oxygen_level_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('oxygen_cannisters', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('\n            oxygen_level_amount <= CASE\n                WHEN oxygen_cannisters = 4 THEN 50\n                ELSE 100\n            END\n            ', name='ck_items_level_cap'),
    sa.CheckConstraint('oxygen_cannisters BETWEEN 0 AND 4', name='ck_items_cannisters_range'),
    sa.CheckConstraint('oxygen_level_amount >= 0', name='ck_items_oxygen_level_non_neg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_items_user_id'), ['user_id'], unique=True)

    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('days_logged_in', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('quizzes_completed', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('modules_completed', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('xp_in_level', sa.Integer(), nullable=False),
    sa.Column('xp_to_next', sa.Integer(), nullable=False),
    sa.CheckConstraint('current_level >= 1', name='ck_stats_current_level_min1'),
    sa.CheckConstraint('days_logged_in >= 0', name='ck_stats_days_logged_in_non_neg'),
    sa.CheckConstraint('modules_completed >= 0', name='ck_stats_modules_non_neg'),
    sa.CheckConstraint('quizzes_completed >= 0', name='ck_stats_quizzes_non_neg'),
    sa.CheckConstraint('total_xp >= 0', name='ck_stats_total_xp_non_neg'),
    sa.CheckConstraint('xp_in_level >= 0', name='ck_stats_xp_in_level_non_neg'),
    sa.CheckConstraint('xp_to_next > 0', name='ck_stats_xp_to_next_pos'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.create_index('ix_user_stats_total_xp', ['total_xp'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stats_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stats_user_id'))
        batch_op.drop_index('ix_user_stats_total_xp')

    op.drop_table('user_stats')
    with op.batch_alter_table('user_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_items_user_id'))

    op.drop_table('user_items')
    op.drop_table('user_badges')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_age'))

    op.drop_table('users')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_slug'))

    op.drop_table('badges')
    # ### end Alembic commands ###
